[project]
name = "DLCFastTravel"
version = "1.0.1"
authors = [{ name = "Yeti, Miner" } ]
description = "Adds fast travels to all of the story DLCs. Works coop!"

[tool.sdkmod]
name = "DLC Fast Travel"
download = "https://github.com/RedxYeti/Yeti-BL1-SDK-Mods/raw/refs/heads/main/DLCFastTravelSDK/DLCFastTravelSDK.zip"
