RolandComs= [
    'gd_CommandDecks.Body_Roland.Roland_Commando',
    'gd_CommandDecks.Body_Roland.Roland_HeavyGunner',
    'gd_CommandDecks.Body_Roland.Roland_Leader',
    'gd_CommandDecks.Body_Roland.Roland_Rifleman',
    'gd_CommandDecks.Body_Roland.Roland_ShockTrooper',
    'gd_CommandDecks.Body_Roland.Roland_SupportGunner',
    'gd_CommandDecks.Body_Roland.Roland_Tactician',
    'dlc3_gd_CommandDecks.Body_Command.Roland_Dahl_Marine',
    'dlc3_gd_CommandDecks.Body_Loyalty.Loyalty_Roland_Vladof',
    'dlc3_gd_CommandDecks.Body_Loyalty.Loyalty_Roland_SandS',
    'dlc3_gd_CommandDecks.Body_Loyalty.Loyalty_Roland_Atlas',
]

LilithComs = [
    'gd_CommandDecks.Body_Lilith.Lilith_Catalyst',
    'gd_CommandDecks.Body_Lilith.Lilith_Defender',
    'gd_CommandDecks.Body_Lilith.Lilith_Firefly',
    'gd_CommandDecks.Body_Lilith.Lilith_Mercenary',
    'gd_CommandDecks.Body_Lilith.Lilith_Plaguebearer',
    'gd_CommandDecks.Body_Lilith.Lilith_Tempest',
    'gd_CommandDecks.Body_Lilith.Lilith_Tormentor',
    'dlc3_gd_CommandDecks.Body_Command.Lilith_Hyperion_Specter',
    'dlc3_gd_CommandDecks.Body_Loyalty.Loyalty_Lilith_Dahl',
    'dlc3_gd_CommandDecks.Body_Loyalty.Loyalty_Lilith_Maliwan',
    'dlc3_gd_CommandDecks.Body_Loyalty.Loyalty_Lilith_Eridian',
]

MordecaiComs = [
    'gd_CommandDecks.Body_Mordecai.Mordecai_Assassin',
    'gd_CommandDecks.Body_Mordecai.Mordecai_Gunslinger',
    'gd_CommandDecks.Body_Mordecai.Mordecai_Hunter',
    'gd_CommandDecks.Body_Mordecai.Mordecai_Ranger',
    'gd_CommandDecks.Body_Mordecai.Mordecai_Scavenger',
    'gd_CommandDecks.Body_Mordecai.Mordecai_Sniper',
    'gd_CommandDecks.Body_Mordecai.Mordecai_Survivor',
    'dlc3_gd_CommandDecks.Body_Command.Mordecai_SandS_Truxican',
    'dlc3_gd_CommandDecks.Body_Loyalty.Loyalty_Mordecai_Jakobs',
    'dlc3_gd_CommandDecks.Body_Loyalty.Loyalty_Mordecai_Hyperion',
    'dlc3_gd_CommandDecks.Body_Loyalty.Loyalty_Mordecai_Anshin',
]

BrickComs = [
    'gd_CommandDecks.Body_Brick.Brick_Berskerker',
    'gd_CommandDecks.Body_Brick.Brick_BlastMaster',
    'gd_CommandDecks.Body_Brick.Brick_Bombardier',
    'gd_CommandDecks.Body_Brick.Brick_Centurion',
    'gd_CommandDecks.Body_Brick.Brick_Skirmisher',
    'gd_CommandDecks.Body_Brick.Brick_Titan',
    'gd_CommandDecks.Body_Brick.Brick_Warmonger',
    'dlc3_gd_CommandDecks.Body_Command.Brick_Torgue_Ogre',
    'dlc3_gd_CommandDecks.Body_Loyalty.Loyalty_Brick_Tediore',
    'dlc3_gd_CommandDecks.Body_Loyalty.Loyalty_Brick_Torgue',
    'dlc3_gd_CommandDecks.Body_Loyalty.Loyalty_Brick_Pangolin',
]

AllBuffedSkills = {
    'gd_Skills2_Brick.Tank.Endowed': 'gd_Skills2_Brick.SkillGradeModifiers.SkillGradeModifier_Brick_Endowed',
    'gd_Skills2_Brick.Brawler.HeavyHanded': 'gd_Skills2_Brick.SkillGradeModifiers.SkillGradeModifier_Brick_HeavyHanded',
    'gd_Skills2_Brick.Blaster.CastIron': 'gd_Skills2_Brick.SkillGradeModifiers.SkillGradeModifier_Brick_CastIron',
    'gd_Skills2_Brick.Brawler.EndlessRage': 'gd_Skills2_Brick.SkillGradeModifiers.SkillGradeModifier_Brick_EndlessRage',
    'gd_Skills2_Brick.Brawler.BloodSport': 'gd_Skills2_Brick.SkillGradeModifiers.SkillGradeModifier_Brick_BloodSport',
    'gd_Skills2_Brick.Blaster.Liquidate': 'gd_Skills2_Brick.SkillGradeModifiers.SkillGradeModifier_Brick_Liquidate',
    'gd_Skills2_Brick.Blaster.Revenge': 'gd_Skills2_Brick.SkillGradeModifiers.SkillGradeModifier_Brick_Revenge',
    'gd_Skills2_Brick.Blaster.MasterBlaster': 'gd_Skills2_Brick.SkillGradeModifiers.SkillGradeModifier_Brick_MasterBlaster',
    'gd_Skills2_Brick.Blaster.RapidReload': 'gd_Skills2_Brick.SkillGradeModifiers.SkillGradeModifier_Brick_RapidReload',
    'gd_Skills2_Brick.Blaster.WideLoad': 'gd_Skills2_Brick.SkillGradeModifiers.SkillGradeModifier_Brick_WideLoad',
    'gd_Skills2_Brick.Tank.Safeguard': 'gd_Skills2_Brick.SkillGradeModifiers.SkillGradeModifier_Brick_Safeguard',
    'gd_Skills2_Brick.Tank.Hardened': 'gd_Skills2_Brick.SkillGradeModifiers.SkillGradeModifier_Brick_Hardened',
    'gd_Skills2_Brick.Tank.Diehard': 'gd_Skills2_Brick.SkillGradeModifiers.SkillGradeModifier_Brick_Diehard',
    'gd_Skills2_Brick.Brawler.ShortFuse': 'gd_Skills2_Brick.SkillGradeModifiers.SkillGradeModifier_Brick_ShortFuse',
    'gd_Skills2_Brick.Brawler.StingLikeaBee': 'gd_Skills2_Brick.SkillGradeModifiers.SkillGradeModifier_Brick_StingLikeaBee',
    'gd_Skills2_Brick.Tank.Bash': 'gd_Skills2_Brick.SkillGradeModifiers.SkillGradeModifier_Brick_Bash',
    'gd_Skills2_Brick.Tank.Unbreakable': 'gd_Skills2_Brick.SkillGradeModifiers.SkillGradeModifier_Brick_Unbreakable',
    'gd_Skills2_Brick.Tank.Juggernaut': 'gd_Skills2_Brick.SkillGradeModifiers.SkillGradeModifier_Brick_Juggernaut',
    'gd_Skills2_Brick.Tank.PayBack': 'gd_Skills2_Brick.SkillGradeModifiers.SkillGradeModifier_Brick_PayBack',

    'gd_Skills2_Lilith.Elemental.Phoenix': 'gd_Skills2_Lilith.SkillGradeModifiers.SkillGradeModifier_Lilith_Phoenix',
    'gd_Skills2_Lilith.Controller.GirlPower': 'gd_Skills2_Lilith.SkillGradeModifiers.SkillGradeModifier_Lilith_GirlPower',
    'gd_Skills2_Lilith.Elemental.Intuition': 'gd_Skills2_Lilith.SkillGradeModifiers.SkillGradeModifier_Lilith_Intuition',
    'gd_Skills2_Lilith.Elemental.Resilience': 'gd_Skills2_Lilith.SkillGradeModifiers.SkillGradeModifier_Lilith_Resilience',
    'gd_Skills2_Lilith.Controller.Diva': 'gd_Skills2_Lilith.SkillGradeModifiers.SkillGradeModifier_Lilith_Diva',
    'gd_Skills2_Lilith.Controller.InnerGlow': 'gd_Skills2_Lilith.SkillGradeModifiers.SkillGradeModifier_Lilith_InnerGlow',
    'gd_Skills2_Lilith.Elemental.Spark': 'gd_Skills2_Lilith.SkillGradeModifiers.SkillGradeModifier_Lilith_Spark',
    'gd_Skills2_Lilith.Elemental.Quicksilver': 'gd_Skills2_Lilith.SkillGradeModifiers.SkillGradeModifier_Lilith_Quicksilver',
    'gd_Skills2_Lilith.Assassin.HighVelocity': 'gd_Skills2_Lilith.SkillGradeModifiers.SkillGradeModifier_Lilith_HighVelocity',
    'gd_Skills2_Lilith.Elemental.Venom': 'gd_Skills2_Lilith.SkillGradeModifiers.SkillGradeModifier_Lilith_Venom',
    'gd_Skills2_Lilith.Controller.MindGames': 'gd_Skills2_Lilith.SkillGradeModifiers.SkillGradeModifier_Lilith_MindGames',
    'gd_Skills2_Lilith.Controller.DramaticEntrance': 'gd_Skills2_Lilith.SkillGradeModifiers.SkillGradeModifier_Lilith_DramaticEntrance',
    'gd_Skills2_Lilith.Elemental.Radiance': 'gd_Skills2_Lilith.SkillGradeModifiers.SkillGradeModifier_Lilith_Radiance',
    'gd_Skills2_Lilith.Assassin.Slayer': 'gd_Skills2_Lilith.SkillGradeModifiers.SkillGradeModifier_Lilith_Slayer',
    'gd_Skills2_Lilith.Assassin.Enforcer': 'gd_Skills2_Lilith.SkillGradeModifiers.SkillGradeModifier_Lilith_Enforcer',
    'gd_Skills2_Lilith.Assassin.SilentResolve': 'gd_Skills2_Lilith.SkillGradeModifiers.SkillGradeModifier_Lilith_SilentResolve',
    'gd_Skills2_Lilith.Controller.Striking': 'gd_Skills2_Lilith.SkillGradeModifiers.SkillGradeModifier_Lilith_Striking',

    'gd_skills2_Mordecai.Gunslinger.Deadly': 'gd_skills2_Mordecai.SkillGradeModifiers.SkillGradeModifier_Mordecai_Deadly',
    'gd_skills2_Mordecai.Gunslinger.LethalStrike': 'gd_skills2_Mordecai.SkillGradeModifiers.SkillGradeModifier_Mordecai_LethalStrike',
    'gd_skills2_Mordecai.Sniper.Killer': 'gd_skills2_Mordecai.SkillGradeModifiers.SkillGradeModifier_Mordecai_Killer',
    'gd_skills2_Mordecai.Gunslinger.GunCrazy': 'gd_skills2_Mordecai.SkillGradeModifiers.SkillGradeModifier_Mordecai_GunCrazy',
    'gd_skills2_Mordecai.Sniper.Focus': 'gd_skills2_Mordecai.SkillGradeModifiers.SkillGradeModifier_Mordecai_Focus',
    'gd_skills2_Mordecai.Sniper.Loaded': 'gd_skills2_Mordecai.SkillGradeModifiers.SkillGradeModifier_Mordecai_Loaded',
    'gd_skills2_Mordecai.Gunslinger.Relentless': 'gd_skills2_Mordecai.SkillGradeModifiers.SkillGradeModifier_Mordecai_Relentless',
    'gd_skills2_Mordecai.Rogue.AerialImpact': 'gd_skills2_Mordecai.SkillGradeModifiers.SkillGradeModifier_Mordecai_AerialImpact',
    'gd_skills2_Mordecai.Rogue.SwiftStrike': 'gd_skills2_Mordecai.SkillGradeModifiers.SkillGradeModifier_Mordecai_SwiftStrike',
    'gd_skills2_Mordecai.Rogue.OutForBlood': 'gd_skills2_Mordecai.SkillGradeModifiers.SkillGradeModifier_Mordecai_OutForBlood',
    'gd_skills2_Mordecai.Gunslinger.RiotousRemedy': 'gd_skills2_Mordecai.SkillGradeModifiers.SkillGradeModifier_Mordecai_RiotousRemedy',
    'gd_skills2_Mordecai.Sniper.Trespass': 'gd_skills2_Mordecai.SkillGradeModifiers.SkillGradeModifier_Mordecai_Trespass',
    'gd_skills2_Mordecai.Gunslinger.Predator': 'gd_skills2_Mordecai.SkillGradeModifiers.SkillGradeModifier_Mordecai_Predator',
    'gd_skills2_Mordecai.Rogue.BirdOfPrey': 'gd_skills2_Mordecai.SkillGradeModifiers.SkillGradeModifier_Mordecai_BirdOfPrey',
    'gd_skills2_Mordecai.Rogue.Swipe': 'gd_skills2_Mordecai.SkillGradeModifiers.SkillGradeModifier_Mordecai_Swipe',
    'gd_skills2_Mordecai.Rogue.Ransack': 'gd_skills2_Mordecai.SkillGradeModifiers.SkillGradeModifier_Mordecai_Ransack',
    'gd_skills2_Mordecai.Sniper.Caliber': 'gd_skills2_Mordecai.SkillGradeModifiers.SkillGradeModifier_Mordecai_Caliber',
    'gd_skills2_Mordecai.Sniper.CarrionCall': 'gd_skills2_Mordecai.SkillGradeModifiers.SkillGradeModifier_Mordecai_CarrionCall',
    'gd_skills2_Mordecai.Rogue.FastHands': 'gd_skills2_Mordecai.SkillGradeModifiers.SkillGradeModifier_Mordecai_FastHands',

    'gd_skills2_Roland.Medic.Fitness': 'gd_skills2_Roland.SkillGradeModifiers.SkillGradeModifier_Roland_Fitness',
    'gd_skills2_Roland.Medic.Grit': 'gd_skills2_Roland.SkillGradeModifiers.SkillGradeModifier_Roland_Grit',
    'gd_skills2_Roland.Support.Impact': 'gd_skills2_Roland.SkillGradeModifiers.SkillGradeModifier_Roland_Impact',
    'gd_skills2_Roland.Infantry.Scattershot': 'gd_skills2_Roland.SkillGradeModifiers.SkillGradeModifier_Roland_Scattershot',
    'gd_skills2_Roland.Support.Defense': 'gd_skills2_Roland.SkillGradeModifiers.SkillGradeModifier_Roland_Defense',
    'gd_skills2_Roland.Support.QuickCharge': 'gd_skills2_Roland.SkillGradeModifiers.SkillGradeModifier_Roland_QuickCharge',
    'gd_skills2_Roland.Infantry.MetalStorm': 'gd_skills2_Roland.SkillGradeModifiers.SkillGradeModifier_Roland_MetalStorm',
    'gd_skills2_Roland.Medic.Overload': 'gd_skills2_Roland.SkillGradeModifiers.SkillGradeModifier_Roland_Overload',
    'gd_skills2_Roland.Infantry.Assault': 'gd_skills2_Roland.SkillGradeModifiers.SkillGradeModifier_Roland_Assault',
    'gd_skills2_Roland.Support.deploy': 'gd_skills2_Roland.SkillGradeModifiers.SkillGradeModifier_Roland_deploy',
    'gd_skills2_Roland.Support.Grenadier': 'gd_skills2_Roland.SkillGradeModifiers.SkillGradeModifier_Roland_Grenadier',
    'gd_skills2_Roland.Medic.Cauterize': 'gd_skills2_Roland.SkillGradeModifiers.SkillGradeModifier_Roland_Cauterize',
    'gd_skills2_Roland.Infantry.Refire': 'gd_skills2_Roland.SkillGradeModifiers.SkillGradeModifier_Roland_Refire',
    'gd_skills2_Roland.Support.Barrage': 'gd_skills2_Roland.SkillGradeModifiers.SkillGradeModifier_Roland_Barrage',
    'gd_skills2_Roland.Support.Stockpile': 'gd_skills2_Roland.SkillGradeModifiers.SkillGradeModifier_Roland_Stockpile',
    'gd_skills2_Roland.Medic.AidStation': 'gd_skills2_Roland.SkillGradeModifiers.SkillGradeModifier_Roland_AidStation',
}