import unrealsdk 
import json
import os
import math

from unrealsdk import find_all, load_package,make_struct,find_object,construct_object, find_class
from unrealsdk.hooks import Type, Block
from unrealsdk.unreal import UObject, WrappedStruct, BoundFunction, WeakPointer, UClass
from mods_base import hook, get_pc, ENGINE, SETTINGS_DIR, SliderOption, BoolOption, SpinnerOption, build_mod
from random import choice, randint



MapNames: list = [
    "arid_p",
    "Arid_SkagGully_P",
    "Arid_Mine_P",
    "Arid_Bunker_P",
    "interlude_1_p",
    "Trash_p",
    "scrap_p",
    "scrap_trashcoast_p",
    "Scrap_Canyon_P",
    "scrap_scrapyard_p",
    "Scrap_OldHaven_P",
    "Interlude_2_Cave_P",
    "Waste_Crimson_P",
    "Interlude_2_P",
    "Waste_Vault_P",
    "Scrap_TrashCave_P",
    "Dry_P",
    "dlc1_island_p",
    "dlc1_swamp_ned_p",
    "dlc1_mill_p",
    "dlc1_zombieHaven_P",
    "dlc1_monsterhouse_p",
    "dlc1_mill_boss_p",
    "dlc2_hellburb_p",
    "dlc2_ruins_p",
    "dlc3_HUB_p",
    "dlc3_NLanceStrip_p",
    "dlc3_lakebed_p",
    "dlc3_prison_p",
    "dlc3_southlake_p",
    "dlc3_uberboss_p",
    "dlc3_lancedepot_p",
    "dlc3_circle_p",
    "dlc3_gondola_p",
    "DLC4_Tartarus_Station_p",
    "DLC4_Hyperion_Dump_p",
    "DLC4_Sanders_Gorge_p",
    "DLC4_SS_Canyon_p",
    "DLC4_Dividing_Faults_p",
    "DLC4_Wayward_Pass_p",
    "DLC4_Arid_Badlands_p",
]


TurretNames: list = [
    "Gatling Turret",
    "Rocket Turret",
    "Gatling Turret-Trap",
    "Missile Turret",
    "Scorpio",
    "Lance Aid Station Scorpio",
    "Shock Scorpio",
    "Flame Thrower Scorpio",
    "Corrosive Scorpio",
    "Scorpio-Trap",
]

BlacklistNames: list = [
    #"Tongue",
    "Swatter",
    "Head",
    "Spike"
]


GruntNames: list = [
    "Tongue",
    "Adult Skag",
    "Elder Skag",
    "Pup Skag",
    "Spitter Skag",
    "Skag Whelp",
    "Bandit Raider",
    "Bandit Thug",
    "Bandit Killer",
    "Bruiser",
    "Midget Shotgunner",
    "Psycho",
    "Burning Psycho",
    "Guardian Spectre",
    "Guardian Wraith",
    "Giant Scythid",
    "Desert Scythid",
    "Scythid Crawler",
    "Bursting Scythid",
    "Spiderantling",
    "Spiderant Worker",
    "Spiderant Soldier",
    "Spiderant Queen",
    "Spiderant King",
    "Spiderant Gyro",
    "Larva Crab Worm",
    "Lance Engineer",
    "Lance Defender",
    "Lance Infantry",
    "Principal Guardian",
    "Arch Guardian",
    "Zombie",
    "Torso",
    "Suicide Zombie",
    "Defiler",
    "Psycho Zombie",
    "Midget Zombie",
    "WereSkag",
    "Lance Zombie",
    "Lance Assassin",
    "Devastator",
    "Lance Shock Trooper",
    "Lance Combat Medic",
    "Lance Infantry",
    "Lance Pyro",
    "Lance Engineer",
    "Lance Infantry",
    "Lance Defender",
    "Lance Chemical Trooper",
    "Midget Ravager",
    "Midget Rustler",
    "Midget Skag Rider",
    "Skag Rustler",
    "Skag Ravager",
    "Skag Raider",
    "Midget Raider",
    "Drifter",
    "Killer",
    "Outlaw",
    "Desperado",
    "Punk",
    "Enforcer",
    "Banger",
    "Claptrap Partisan",
    "Stabby Claptrap ",
    "Burning Psycho-Trap",
    "Bruiser-Trap",
    "Bandit-Trap Killer",
    "Bandit-Trap Thug",
    "Skag-Trap Whelp",
    "Spitter Skag-Trap",
    "Pup Skag-Trap",
    "Elder Skag-Trap",
    "Adult Skag-Trap",
    "Hyperion Tech-Trap",
    "Hyperion Soldier-Trap",
    "Hyperion Guard-Trap",
    "Hyperion Tech",
    "Hyperion Soldier",
    "Hyperion Soldier",
    "Hyperion Guard",
    "Kamikaze Claptrap ",
    "Larva Crab-Trap",
    "Spiderant-Trapling",
    "Spiderant-Trap Worker",
    "Spiderant-Trap Soldier",
    "Spiderant-Trap Queen",
    "Spiderant-Trap King",
    "Spiderant-Trap Gyro",
    "D-Fault Psycho",
    "D-Fault Bandit Thug",
    "Bandit-Trap Raider",
    "Mutant Midget Psycho",
]

FlyingGruntNames: list = [
    "Rakk",
    "Bloated Rakk",
    "Feeder Rakk",
    "Kamikaze Rakk",
    "Defender Rakk",
    "Corpse Eater",
    "Feeder Rakk-Trap",
    "Bloated Rakk-Trap",
    "Rakk-Trap",
    "Kamikaze Rakk-Trap",
    "Defender Rakk-Trap",
    "Skelerakk",
    "Sera Guardian",
    "Lance Rocketeer",
    "Trash Feeder ",
]

BadassNames: list = [
    "Badass Corrosive Alpha",
    "Badass Fire Alpha",
    "Badass Shock Alpha",
    "Alpha Skag",
    "Badass Skag",
    "Badass Corrosive Skag",
    "Badass Fire Skag",
    "Badass Shock Skag",
    "Badass Psycho",
    "Badass Raider",
    "Badass Bruiser",
    "Badass Shock Scythid",
    "Badass Fire Crawler",
    "Badass Poison Scythid",
    "Badass Spiderant Zapper",
    "Badass Spiderant Burner",
    "Badass Spiderant Corrupter",
    "Badass Engineer",
    "Badass Defender",
    "Badass Infantry",
    "Lance Royal Guard",
    "Badass Guardian",
    "Badass Tankenstein",
    "Loot Goon",
    "Badass Lance Assassin",
    "Badass Shock Trooper",
    "Badass Infantry",
    "Badass Pyro",
    "Badass Engineer",
    "Badass Defender",
    "Badass Chemical Trooper",
    "Badass Midget",
    "Badass Skag Rider",
    "Badass Desperado",
    "Badass Thug",
    "Wild Alpha Skag",
    "Green Craw Worm",
    "Armored Craw Worm",
    "Craw Maggot",
    "Badass Devastator",
    "Badass Psycho-Trap",
    "Badass Bruiser-Trap",
    "Badass Skag-Trap",
    "Alpha Skag-Trap",
    "Badass Shock Alpha Skag-Trap",
    "Badass Fire Alpha Skag-Trap",
    "Badass Corrosive Alpha Skag-Trap",
    "Badass Hyperion Tech-Trap",
    "Badass Hyperion Soldier-Trap",
    "Badass Hyperion Guard-Trap",
    "Badass Spiderant-Trap Zapper",
    "Badass Spiderant-Trap Burner",
    "Badass Spiderant-Trap Corrupter",
    "Badass Raider-Trap",
    "Badass Drifter",
    "Meat Popsicle",
    "Dumpster Diver",
    "Mini Steve",
    "Truxican Wrestler",
    "Crimson Shorty",
    "Skag Rapparee",
    "Badass Shock Skag-Trap",
    "Badass Fire Skag-Trap",
    "Badass Corrosive Skag-Trap",
]

FlyingBadassNames = [
    "Badass Shock Rakk",
    "Badass Fire Rakk",
    "Badass Corrosive Rakk",
    "Badass Rocketeer",
    "Badass Shock Rakk-Trap",
    "Badass Fire Rakk-Trap",
    "Badass Corrosive Rakk-Trap",
    "Lance Probe",
]


BossNames: list = [
    "Bone Head",
    "Nine-Toes",
    "Pinky",
    "Digit",
    "Scar",
    "Sledge",
    "Roid Rage Psycho",
    "Skagzilla",
    "Widowmaker",
    "Helob",
    "Slither",
    "Jaynis Kobb",
    "Taylor Kobb",
    "One-Eyed Jack",
    "Queen Tarantella",
    "King Aracobb",
    "Bleeder",
    "Rakk Hive",
    "Reaver",
    "Krom",
    "Master McCloud",
    "Hanz",
    "Franz",
    "Baron Flynt",
    "The Destroyer",
    "King Wee Wee",
    "Moe",
    "Marley",
    "Franken Bill",
    "Hank Reiss",
    "Whiskey Wesley",
    "Red Jack",
    "Father O'Callahan",
    "Bigfoot",
    "Undead Ned",
    "Ned",
    "Vulcana",
    "Motor Head",
    "Minerva",
    "Commander Kyros",
    "Commander Typhon",
    " Skyscraper ",
    "Shank",
    "Chaz",
    "Hera",
    "Crawmerax the Invincible",
    "General Knoxx",
    "Helicon",
    "Ceresia",
    "General Knoxx-Trap",
    "Cluck-Trap",
    "Rakk-Trap Hive",
    "Dr. Ned-Trap",
    "D-Fault",
    "Comandant Steele-Trap",
    "Undead Ned-Trap",
    "MINAC",
    "Interplanetary Ninja Assassin Claptrap",
    "Pumpkin Head",
    'Skrappy "all grown up"',
    "Hyperion 'Super-Bad' Soldier",
]

FlyingBossNames: list = [
    "Mothrakk",
    "Rakkinishu",
    "Ajax",
]



VehicleNames: list = [
    "Cheta Paw",
    "Crimson Lancer",
    "Out Rider",
    "Mad Mel",
    "Krom's Turret",
    "Mulciber Mk2",
]



CarPacks: list = [
    "gd_DLC3_Cheetah_Paw",
    "gd_DLC3_Lancer",
    "gd_DLC3_Stunt_Runner",
    "gd_outrider",
    "gd_CheetahsPaw",
    "gd_banditkromboss",
]
